server:
  port: 8082
spring:
  application:
    name: cart-service
  profiles:
    active: dev
    include: nacos
  cloud:
    nacos:
      discovery:
        server-addr: ${hm.nacos.server-addr}

hm:
  swagger:
    title: 黑马商城购物车接口文档
    description: "黑马商城购物车接口文档"
    package: com.hmall.cart.controller