server:
  port: 8082
  #tomcat的配置用于 微服务的线程隔离 测试
  tomcat:
    threads:
      max: 25
    max-connections: 100
    accept-count: 50


spring:
  application:
    name: cart-service
  profiles:
    active: dev
    include: nacos
  cloud:
    nacos:
      discovery:
        server-addr: ${hm.nacos.server-addr}
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true

hm:
  swagger:
    title: 黑马商城购物车接口文档
    description: "黑马商城购物车接口文档"
    package: com.hmall.cart.controller